### ISSUE TITLE
Problems on "yoffset * region.numx + xoffset" in SpatialRegionTools.jl, 120

### ISSUE THREAD

**Issue by V-Enzo** [boathit/t2vec#10]
> """
> Web Mercator coordinate to cell id
> """
> function coord2cell(region::SpatialRegion, x::Float64, y::Float64)
>     xoffset = round(x - region.minx, digits=6) / region.xstep
>     yoffset = round(y - region.miny, digits=6) / region.ystep
>     xoffset = convert(Int, floor(xoffset))
>     yoffset = convert(Int, floor(yoffset))
>     yoffset * region.numx + xoffset
> end
Hi @boathit , in your preprocessing part in file SpatialRegionTools.jl line 120, I feel confused when you project coordinates into cells here. From my understanding, every cell we defined should be assigned an  
id, which could be from 0 to vocab_size-1. But here the id equals  yoffset * region.numx + xoffset. Why is this?  Thank you.

**Comment by boathit** [comment]
The cell id does not range over `[0, vocab_size-1]`, it is transformed into vocabulary in [this line](https://github.com/boathit/t2vec/blob/master/preprocessing/SpatialRegionTools.jl#L200).

**Comment by V-Enzo** [comment]
> The cell id does not range over `[0, vocab_size-1]`, it is transformed into vocabulary in [this line](https://github.com/boathit/t2vec/blob/master/preprocessing/SpatialRegionTools.jl#L200).

@boathit I see, so the cell id is related to the number of the size of hot cell. If I set the hyper parameter of `frequent` to 1, which means I take every cell of the map into consideration. Will the vocab size be equal to the number of all cells on the map? Meanwhile, I still don't understand why do you transform coordinates to cell id by `yoffset * region.numx + xoffset` ? Really appreciate it if you could explain this. Thank you.

**Comment by boathit** [comment]
For the first question, the answer is yes. Transforming coordinates into cell ids is just the process of discretization, in which `(xoffset, yoffset)` is the cell coordinate and `region.numx` is the number of columns, `yoffset * region.numx + xoffset` simply transforms the 2D array into a 1D array.

**Comment by V-Enzo** [comment]
Thanks. I know your main idea now. Appreciate it!
