### ISSUE TITLE
Haven't found the definition of "injectnoise()"

### ISSUE THREAD

**Issue by C-Harlin** [boathit/t2vec#12]
Hi, I'm new to Julia and I noticed that injectnoise() was used without exactly defined.
All I found throughout the codes with the "injectnoise" are only two lines:L311,L325
https://github.com/boathit/t2vec/blob/d09f17ca18f8e6f2d8f0d586fffac6969dfeff64/preprocessing/SpatialRegionTools.jl#L309-L325

The code works, so I must have some misunderstanding there.
Could anyone tell me where I am wrong?

**Comment by boathit** [comment]
`injectnoise` is an argument of `createTrainVal`, i.e., it is a variable and can be any function you pass to `createTrainVal`. For example, the call `createTrainVal(region, "porto.h5", downsampling, 50, 10)` instantiates `injectnoise` to be `downsampling` which is defined [here](https://github.com/boathit/t2vec/blob/d09f17ca18f8e6f2d8f0d586fffac6969dfeff64/preprocessing/utils.jl#L106).

**Comment by C-Harlin** [comment]
Thanks for your quick reply! I just realized what a simply question I asked. Thx!
