### ISSUE TITLE
Embedding with vocab size out of bounds

### ISSUE THREAD

**Issue by Scottdyt** [boathit/t2vec#17]
Hi,

When I upgrade pytorch to the lastest version, I got the error when get vocab from decoder:

```
File "/home/d2tec/train.py", line 51, in KLDIVloss
    outputk = torch.gather(output, 1, indices)
RuntimeError: index 18864 is out of bounds for dimension 1 with size 18864
```

Since the vocab_size in network is 18864, when using `index_select` to select topk ID from target, it is possibe to select ID = 18864/18865, but the output just has 18864 demension, so the problem arises. 

https://github.com/boathit/t2vec/blob/f518c3ed4db8aee1d59d4ba1cf7b0f7a59c6137a/train.py#L31

I am really confused about the error, because it only appeard when I upgrade pytorch. 

I dont know whether I understand correctly, hope to see your reply. A lot thanks!

**Comment by Scottdyt** [comment]
The `vocab_size` of the preprocess ouputs is `18866`, I am wondering why you pass `18864` as the `vocab_size` in parameter of the network?

**Comment by boathit** [comment]
The `vocab_size` should be the output of your preprocessing step. That value might be slightly different depending on your Julia version, previously the code was written in Julia 0.6 which yields 18864.

**Comment by Scottdyt** [comment]
Ok I got it, thanks for your patient reply!
