### ISSUE TITLE
Problem when training 

### ISSUE THREAD

**Issue by maaeedee** [boathit/t2vec#25]
Hi, 

I could successfully run the data generation and preprocessing code. I faced the below error when training the model:
RuntimeError: CUDA error: device-side assert triggered

Then I realized that I can solve this error by running on CPU rather than CPU. Then I faced the below error:
Traceback (most recent call last):
  File "t2vec.py", line 121, in <module>
    train(args)
  File "/data/nasrim/t2vec/train.py", line 260, in train
    genloss = genLoss(gendata, m0, m1, lossF, args)
  File "/data/nasrim/t2vec/train.py", line 103, in genLoss
    loss += lossF(o, t)
  File "/data/nasrim/t2vec/train.py", line 207, in <lambda>
    lossF = lambda o, t: KLDIVloss(o, t, criterion, V, D)
  File "/data/nasrim/t2vec/train.py", line 42, in KLDIVloss
    outputk = torch.gather(output, 1, indices)
RuntimeError: Invalid index in gather at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:472

It seems that the index is wrong? Could you please help me to solve this issue?

**Comment by boathit** [comment]
It seems to be the PyTorch version incompatible issue, please try PyTorch 1.5 and let me know if the error still shows up.

**Comment by maaeedee** [comment]
Thanks for your help. This was indeed the issue. The error is gone by PyTorch 1.5.
Before, I tried 1.3 and 1.6 and failed to run successfully.
