### ISSUE TITLE
Harbin data set from original paper

### ISSUE THREAD

**Issue by ZrrrKIT** [boathit/t2vec#4]
Hello boathit,

In the original paper you use two data sets - one from Porto and one from Harbin. I have been doing some experiments with trajectories from Porto, but I wanted to see whether the experiments will be consistent on another corpora - Harbin. 

Could you please point me to a link where the Harbin trajectories are uploaded?

Best regards,
Zrrr

**Comment by boathit** [comment]
Hi @ZrrrKIT, we have released a 5 days' trajectory data of the Harbin dataset for our WWW19 paper, available at [here](https://github.com/boathit/deepgtt#dataset), but not sure whether it is sufficient for representation learning. The availability of the complete Harbin dataset is subject to the agreement of our partner, and if you are looking for the public large-scale trajectory datasets, I refer you to [this page](https://outreach.didichuxing.com/research/opendata/en/).
